name: smv-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - streamlit
  - matplotlib
  - seaborn
  - openpyxl
  - joblib
  - pip
  - pip:
      - plotly
